// react_frame/05_fetch_promise_github_search/App.jsx
import React, { Component } from 'react'

import Search from "./components/Search"
import List from "./components/List"

export default class App extends Component {


  render() {

    return (
      <div className="container">
        <Search ></Search>
        <List></List>
      </div>
    )
  }
}

// vue2_test/19_Vuex的多组件运用/App.vue
<template>
  <div class="container">
    <VuexCount></VuexCount>
    <br><br>
    <hr>
    <VuexPersons></VuexPersons>

  </div>
</template>
 
<script>
import VuexCount from './components/VuexCount'
import VuexPersons from './components/VuexPersons.vue';

export default {
  name: 'App',
  components: { VuexCount, VuexPersons }
}
</script>

<style></style>
