// react_frame/05_fetch_promise_github_search/App.jsx
import React, { Component } from 'react'

import Search from "./components/Search"
import List from "./components/List"

export default class App extends Component {


  render() {

    return (
      <div className="container">
        <Search ></Search>
        <List></List>
      </div>
    )
  }
}

// vue2_test/16_gitub_search/App.vue
<template>    
    <div class="container">
      <MySearch></MySearch>
      <MyList></MyList>
    </div>
</template>

<script>
import MySearch from '../src/components/MySearch.vue'
import MyList from '../src/components/MyList.vue'
  export default {
    name: 'App',
    components:{MyList, MySearch}
  }
</script>

<style>

</style>
